### ISSUE TITLE
Exception thrown

### ISSUE THREAD

**Issue by borpin** [emoncms/demandshaper#32]
Demandshaper sometimes throws this exception.

This was seen on a restart of the service after a clean install, on Ubuntu, of stable branch - but it does not always happen (sadly).

Suggest code is inserted to catch the exception cleanly.

```
Oct 01 21:14:20 ubunt-emon demandshaper[1971]: PHP Fatal error:  Uncaught ErrorException: Invalid argument supplied for foreach() in /opt/emoncms/modules/demandshaper/demandshaper-module/demandshaper_model.p
Oct 01 21:14:20 ubunt-emon demandshaper[1971]: Stack trace:
Oct 01 21:14:20 ubunt-emon demandshaper[1971]: #0 /opt/emoncms/modules/demandshaper/demandshaper-module/demandshaper_model.php(64): exceptions_error_handler(2, 'Invalid argumen...', '/opt/emoncms/mo...', 64,
Oct 01 21:14:20 ubunt-emon demandshaper[1971]: #1 /opt/emoncms/modules/demandshaper/demandshaper_run.php(361): DemandShaper->set(1, Object(stdClass))
Oct 01 21:14:20 ubunt-emon demandshaper[1971]: #2 {main}
Oct 01 21:14:20 ubunt-emon demandshaper[1971]:   thrown in /opt/emoncms/modules/demandshaper/demandshaper-module/demandshaper_model.php on line 64
Oct 01 21:14:20 ubunt-emon demandshaper[1971]: Fatal error: Uncaught ErrorException: Invalid argument supplied for foreach() in /opt/emoncms/modules/demandshaper/demandshaper-module/demandshaper_model.php:64
Oct 01 21:14:20 ubunt-emon demandshaper[1971]: Stack trace:
Oct 01 21:14:20 ubunt-emon demandshaper[1971]: #0 /opt/emoncms/modules/demandshaper/demandshaper-module/demandshaper_model.php(64): exceptions_error_handler(2, 'Invalid argumen...', '/opt/emoncms/mo...', 64,
Oct 01 21:14:20 ubunt-emon demandshaper[1971]: #1 /opt/emoncms/modules/demandshaper/demandshaper_run.php(361): DemandShaper->set(1, Object(stdClass))
Oct 01 21:14:20 ubunt-emon demandshaper[1971]: #2 {main}
Oct 01 21:14:20 ubunt-emon demandshaper[1971]:   thrown in /opt/emoncms/modules/demandshaper/demandshaper-module/demandshaper_model.php on line 64
```

**Comment by TrystanLea** [comment]
This should fix this one https://github.com/emoncms/demandshaper/commit/7fa85eb171b57bde4f97ac0c6c7cb96f90ff7bb6
