### ISSUE TITLE
ubuntu problem

### ISSUE THREAD

**Issue by nobless** [emoncms/demandshaper#59]
root@ubuntu:~#  service demandshaper status
● demandshaper.service - Emoncms Demandshaper service
   Loaded: loaded (/lib/systemd/system/demandshaper.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2020-11-02 01:10:10 EET; 4s ago
     Docs: https://github.com/emoncms/demandshaper/blob/master/readme.md
  Process: 2230 ExecStart=/usr/bin/php /opt/emoncms/modules/demandshaper/demandshaper_run.php (code=exited, status=255)
 Main PID: 2230 (code=exited, status=255)

Nov 02 01:10:10 ubuntu systemd[1]: demandshaper.service: Main process exited, code=exited, status=255/n/a
Nov 02 01:10:10 ubuntu systemd[1]: demandshaper.service: Failed with result 'exit-code'.
root@ubuntu:~#  php /opt/emoncms/modules/demandshaper/demandshaper_run.php
PHP Warning:  Uncaught ErrorException: require_once(Modules/device/device_model.php): failed to open stream: No such file or directory in /opt/emoncms/modules/demandshaper/demandshaper_run.php:72
Stack trace:
#0 /opt/emoncms/modules/demandshaper/demandshaper_run.php(72): exceptions_error_handler()
#1 /opt/emoncms/modules/demandshaper/demandshaper_run.php(72): require_once()
#2 {main}
  thrown in /opt/emoncms/modules/demandshaper/demandshaper_run.php on line 72

Warning: Uncaught ErrorException: require_once(Modules/device/device_model.php): failed to open stream: No such file or directory in /opt/emoncms/modules/demandshaper/demandshaper_run.php:72
Stack trace:
#0 /opt/emoncms/modules/demandshaper/demandshaper_run.php(72): exceptions_error_handler()
#1 /opt/emoncms/modules/demandshaper/demandshaper_run.php(72): require_once()
#2 {main}
  thrown in /opt/emoncms/modules/demandshaper/demandshaper_run.php on line 72
PHP Fatal error:  main(): Failed opening required 'Modules/device/device_model.php' (include_path='.:/usr/share/php') in /opt/emoncms/modules/demandshaper/demandshaper_run.php on line 72

Fatal error: main(): Failed opening required 'Modules/device/device_model.php' (include_path='.:/usr/share/php') in /opt/emoncms/modules/demandshaper/demandshaper_run.php on line 72

**Comment by TrystanLea** [comment]
Hello @nobless sorry for the delay, did you get this sorted?
Looks like you need to install the device module?
